FROM ubuntu:18.04

RUN echo "deb http://mirrors.zju.edu.cn/ubuntu bionic main universe restricted multiverse" > /etc/apt/sources.list \
    && echo "deb http://mirrors.zju.edu.cn/ubuntu bionic-security main universe restricted multiverse" >> /etc/apt/sources.list \
    && echo "deb http://mirrors.zju.edu.cn/ubuntu bionic-updates main universe restricted multiverse" >> /etc/apt/sources.list \
    && echo "deb http://mirrors.zju.edu.cn/ubuntu bionic-backports main universe restricted multiverse" >> /etc/apt/sources.list \
    && echo "deb-src http://mirrors.zju.edu.cn/ubuntu bionic main universe restricted multiverse" >> /etc/apt/sources.list \
    && echo "deb-src http://mirrors.zju.edu.cn/ubuntu bionic-security main universe restricted multiverse" >> /etc/apt/sources.list \
    && echo "deb-src http://mirrors.zju.edu.cn/ubuntu bionic-updates main universe restricted multiverse" >> /etc/apt/sources.list \
    && echo "deb-src http://mirrors.zju.edu.cn/ubuntu bionic-backports main universe restricted multiverse" >> /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y bash-completion vim.tiny openssh-server \
    && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
